### ISSUE TITLE
Trouble getting it to work

### ISSUE THREAD

**Issue by lkrugertogetr** [Quramy/typescript-eslint-language-service#304]
I'm using yarn berry, which does make it more of a pain than it needs to be. Here's some missing dependencies according to yarn:
```yaml
//.yarnrc.yml
packageExtensions:
  typescript-eslint-language-service@*:
    dependencies:
      '@typescript-eslint/scope-manager': '*'
      '@typescript-eslint/visitor-keys': '*'
      'globby': '^11.0.3'
      'is-glob': '*'
      '@eslint/eslintrc': '*'

yarnPath: .yarn/releases/yarn-berry.cjs
```
After that I get the following:
```
Info 33   [14:42:43.011] [typescript-eslint-language-service] config: {"name":"typescript-eslint-language-service"}
Info 34   [14:42:43.012] Plugin activation failed: Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: i:\<repo path>\.yarn\cache\eslint-npm-7.32.0-e15cc6682f-cc85af9985.zip\node_modules\eslint\lib\cli-engine\cascading-config-array-factory
Not found: i:\<repo path>\.yarn\cache\eslint-npm-7.32.0-e15cc6682f-cc85af9985.zip\node_modules\eslint\lib\cli-engine\cascading-config-array-factory
Not found: i:\<repo path>\.yarn\cache\eslint-npm-7.32.0-e15cc6682f-cc85af9985.zip\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
Not found: i:\<repo path>\.yarn\cache\eslint-npm-7.32.0-e15cc6682f-cc85af9985.zip\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.json
Not found: i:\<repo path>\.yarn\cache\eslint-npm-7.32.0-e15cc6682f-cc85af9985.zip\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.node
```

I am using the latest ESLint. After removing the try catch block in `eslint-config-provider.ts` I'm getting the following:
```
Plugin activation failed: Error: Missing "./lib/cascading-config-array-factory" export in "@eslint/eslintrc" package
Require stack:
- i:\<repo path>\.yarn\__virtual__\typescript-eslint-language-service-virtual-cb98ba6b40\0\cache\typescript-eslint-language-service-npm-4.1.5-470c7ddaa3-3d4934bac3.zip\node_modules\typescript-eslint-language-service\lib\eslint-config-provider.js
- i:\<repo path>\.yarn\__virtual__\typescript-eslint-language-service-virtual-cb98ba6b40\0\cache\typescript-eslint-language-service-npm-4.1.5-470c7ddaa3-3d4934bac3.zip\node_modules\typescript-eslint-language-service\lib\plugin-module-factory.js
- i:\<repo path>\.yarn\__virtual__\typescript-eslint-language-service-virtual-cb98ba6b40\0\cache\typescript-eslint-language-service-npm-4.1.5-470c7ddaa3-3d4934bac3.zip\node_modules\typescript-eslint-language-service\lib\index.js
- i:\<repo path>\.yarn\cache\typescript-patch-bb3b548ba1-bc2c4fdf0f.zip\node_modules\typescript\lib\tsserver.js
- i:\<repo path>\.pnp.cjs
```

Edit: after changing `@eslint/eslintrc` version from `*` to `^0.4.3` it loaded correctly.

**Comment by lkrugertogetr** [comment]
After getting it loading correctly I'm getting the following:
```
Info 254  [15:26:13.502] [typescript-eslint-language-service] use '@typescript-eslint/parser'
Info 255  [15:26:13.515] [typescript-eslint-language-service] Error: use '@typescript-eslint/parser'
    at ESLintAdapter.getESLintResult (i:\<repo path>\.yarn\__virtual__\typescript-eslint-language-service-virtual-cb98ba6b40\0\cache\typescript-eslint-language-service-npm-4.1.5-470c7ddaa3-3d4934bac3.zip\node_modules\typescript-eslint-language-service\lib\eslint-adapter.js:92:19)
    at ESLintAdapter.getSemanticDiagnostics (i:\<repo path>\.yarn\__virtual__\typescript-eslint-language-service-virtual-cb98ba6b40\0\cache\typescript-eslint-language-service-npm-4.1.5-470c7ddaa3-3d4934bac3.zip\node_modules\typescript-eslint-language-service\lib\eslint-adapter.js:106:39)
    at IOSession.Session.semanticCheck (i:\<repo path>\.yarn\cache\typescript-patch-bb3b548ba1-bc2c4fdf0f.zip\node_modules\typescript\lib\tsserver.js:164150:52)
    at i:\<repo path>\.yarn\cache\typescript-patch-bb3b548ba1-bc2c4fdf0f.zip\node_modules\typescript\lib\tsserver.js:164206:31
    at MultistepOperation.executeAction (i:\<repo path>\.yarn\cache\typescript-patch-bb3b548ba1-bc2c4fdf0f.zip\node_modules\typescript\lib\tsserver.js:163156:25)
    at i:\<repo path>\.yarn\cache\typescript-patch-bb3b548ba1-bc2c4fdf0f.zip\node_modules\typescript\lib\tsserver.js:163135:100
    at IOSession.Session.executeWithRequestId (i:\<repo path>\.yarn\cache\typescript-patch-bb3b548ba1-bc2c4fdf0f.zip\node_modules\typescript\lib\tsserver.js:165473:28)
    at Object.executeWithRequestId (i:\<repo path>\.yarn\cache\typescript-patch-bb3b548ba1-bc2c4fdf0f.zip\node_modules\typescript\lib\tsserver.js:163918:87)
    at Immediate._onImmediate (i:\<repo path>\.yarn\cache\typescript-patch-bb3b548ba1-bc2c4fdf0f.zip\node_modules\typescript\lib\tsserver.js:163135:41)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by lkrugertogetr** [comment]
Update: changing the deprecated `CLIEngine` to `ESLint` [here](https://github.com/Quramy/typescript-eslint-language-service/blob/master/src/eslint-adapter.ts#L113) solved that issue. However, it is still not working.

The following is happening:
```
Info 391  [08:49:34.998] request:
    {"seq":55,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":["i:/<repo path>/node_modules/typescript-eslint-language-service/lib/eslint-adapter.js"],"openFiles":[]}}
Info 392  [08:49:34.999] FileWatcher:: Close:: WatchInfo: i:/<repo path>/node_modules/typescript-eslint-language-service/lib/tsconfig.json 2000 undefined WatchType: Config file for the inferred project root
Info 393  [08:49:34.999] FileWatcher:: Close:: WatchInfo: i:/<repo path>/node_modules/typescript-eslint-language-service/lib/jsconfig.json 2000 undefined WatchType: Config file for the inferred project root
Info 394  [08:49:34.999] FileWatcher:: Close:: WatchInfo: i:/<repo path>/node_modules/typescript-eslint-language-service/jsconfig.json 2000 undefined WatchType: Config file for the inferred project root
Info 395  [08:49:34.999] FileWatcher:: Close:: WatchInfo: i:/<repo path>/node_modules/tsconfig.json 2000 undefined WatchType: Config file for the inferred project root
Info 396  [08:49:35.000] FileWatcher:: Close:: WatchInfo: i:/<repo path>/node_modules/jsconfig.json 2000 undefined WatchType: Config file for the inferred project root
Info 397  [08:49:35.001] Project 'i:/<repo path>/tsconfig.json' (Configured)
Info 397  [08:49:35.001] 	Files (99)

Info 397  [08:49:35.001] -----------------------------------------------
Info 397  [08:49:35.001] Project 'i:/<repo path>/node_modules/typescript-eslint-language-service/tsconfig.json' (Configured)
Info 397  [08:49:35.001] 	Files (136)

Info 397  [08:49:35.001] -----------------------------------------------
Info 397  [08:49:35.001] Project '/dev/null/inferredProject1*' (Inferred)
Info 397  [08:49:35.001] 	Files (1034)

Info 397  [08:49:35.001] -----------------------------------------------
Info 397  [08:49:35.001] Open files: 
Info 397  [08:49:35.001] 	FileName: i:/<repo path>/src/Test.ts ProjectRootPath: i:/<repo path>
Info 397  [08:49:35.001] 		Projects: i:/<repo path>/tsconfig.json
Perf 397  [08:49:35.001] 55::updateOpen: elapsed time (in milliseconds) 3.5309
Info 398  [08:49:35.001] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":55,"success":true,"body":true}
```
With this none of the ESLint rules are triggered where they should be, at this point I'm starting to get clueless.
