### ISSUE TITLE
TypeScript won't load the module

### ISSUE THREAD

**Issue by ant-fx** [Quramy/typescript-eslint-language-service#506]
I've installed the package locally with NPM but the TypeScript language server is refusing it find it for some reason. With verbose logging enabled I see the following. Notice it does not try to load the module in the local `node_modules` folder.

```
Info 22   [16:53:28.686] Enabling plugin typescript-eslint-language-service from candidate paths: /Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0,/Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5,/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
Info 23   [16:53:28.687] Loading typescript-eslint-language-service from /Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0 (resolved to /Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules)
Info 24   [16:53:28.698] Loading typescript-eslint-language-service from /Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5 (resolved to /Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5/node_modules)
Info 25   [16:53:28.717] Loading typescript-eslint-language-service from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules)
Info 26   [16:53:28.717] Failed to load module 'typescript-eslint-language-service' from /Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules: Error: Could not resolve JS module 'typescript-eslint-language-service' starting at '/Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules'. Looked in: /Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-eslint-language-service/package.json, /Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-eslint-language-service.js, /Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-eslint-language-service.jsx, /Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-eslint-language-service/index.js, /Users/miked/.vscode/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-eslint-language-service/index.jsx, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service/package.json, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service.js, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service.jsx, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service/index.js, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service/index.jsx, /Users/miked/.vscode/node_modules/typescript-eslint-language-service/package.json, /Users/miked/.vscode/node_modules/typescript-eslint-language-service.js, /Users/miked/.vscode/node_modules/typescript-eslint-language-service.jsx, /Users/miked/.vscode/node_modules/typescript-eslint-language-service/index.js, /Users/miked/.vscode/node_modules/typescript-eslint-language-service/index.jsx, /Users/miked/node_modules/typescript-eslint-language-service/package.json, /Users/miked/node_modules/typescript-eslint-language-service.js, /Users/miked/node_modules/typescript-eslint-language-service.jsx, /Users/miked/node_modules/typescript-eslint-language-service/index.js, /Users/miked/node_modules/typescript-eslint-language-service/index.jsx, /Users/node_modules/typescript-eslint-language-service/package.json, /Users/node_modules/typescript-eslint-language-service.js, /Users/node_modules/typescript-eslint-language-service.jsx, /Users/node_modules/typescript-eslint-language-service/index.js, /Users/node_modules/typescript-eslint-language-service/index.jsx, /node_modules/typescript-eslint-language-service/package.json, /node_modules/typescript-eslint-language-service.js, /node_modules/typescript-eslint-language-service.jsx, /node_modules/typescript-eslint-language-service/index.js, /node_modules/typescript-eslint-language-service/index.jsx
    at Object.resolveJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:44257:19)
    at sys.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185768:49)
    at Project.resolveModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173477:35)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174624:36
    at Object.firstDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:221:26)
    at Project.beginEnablePluginSync (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174623:41)
    at ProjectService.requestEnablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178808:49)
    at Project.enablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174687:37)
    at ConfiguredProject.enablePluginsWithOptions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175358:30)
    at ProjectService.loadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177076:25)
    at ProjectService.createAndLoadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177028:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177033:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178119:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178459:97
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178459:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179831:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182024:96
    at Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182015:28)
    at Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182024:41)
    at Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182052:35)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:186208:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
Info 27   [16:53:28.718] Failed to load module 'typescript-eslint-language-service' from /Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5/node_modules: Error: Could not resolve JS module 'typescript-eslint-language-service' starting at '/Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5/node_modules'. Looked in: /Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5/node_modules/typescript-eslint-language-service/package.json, /Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5/node_modules/typescript-eslint-language-service.js, /Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5/node_modules/typescript-eslint-language-service.jsx, /Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5/node_modules/typescript-eslint-language-service/index.js, /Users/miked/.vscode/extensions/styled-components.vscode-styled-components-1.7.5/node_modules/typescript-eslint-language-service/index.jsx, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service/package.json, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service.js, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service.jsx, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service/index.js, /Users/miked/.vscode/extensions/node_modules/typescript-eslint-language-service/index.jsx, /Users/miked/.vscode/node_modules/typescript-eslint-language-service/package.json, /Users/miked/.vscode/node_modules/typescript-eslint-language-service.js, /Users/miked/.vscode/node_modules/typescript-eslint-language-service.jsx, /Users/miked/.vscode/node_modules/typescript-eslint-language-service/index.js, /Users/miked/.vscode/node_modules/typescript-eslint-language-service/index.jsx, /Users/miked/node_modules/typescript-eslint-language-service/package.json, /Users/miked/node_modules/typescript-eslint-language-service.js, /Users/miked/node_modules/typescript-eslint-language-service.jsx, /Users/miked/node_modules/typescript-eslint-language-service/index.js, /Users/miked/node_modules/typescript-eslint-language-service/index.jsx, /Users/node_modules/typescript-eslint-language-service/package.json, /Users/node_modules/typescript-eslint-language-service.js, /Users/node_modules/typescript-eslint-language-service.jsx, /Users/node_modules/typescript-eslint-language-service/index.js, /Users/node_modules/typescript-eslint-language-service/index.jsx, /node_modules/typescript-eslint-language-service/package.json, /node_modules/typescript-eslint-language-service.js, /node_modules/typescript-eslint-language-service.jsx, /node_modules/typescript-eslint-language-service/index.js, /node_modules/typescript-eslint-language-service/index.jsx
    at Object.resolveJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:44257:19)
    at sys.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185768:49)
    at Project.resolveModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173477:35)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174624:36
    at Object.firstDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:221:26)
    at Project.beginEnablePluginSync (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174623:41)
    at ProjectService.requestEnablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178808:49)
    at Project.enablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174687:37)
    at ConfiguredProject.enablePluginsWithOptions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175358:30)
    at ProjectService.loadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177076:25)
    at ProjectService.createAndLoadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177028:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177033:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178119:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178459:97
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178459:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179831:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182024:96
    at Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182015:28)
    at Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182024:41)
    at Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182052:35)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:186208:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
Info 28   [16:53:28.718] Failed to load module 'typescript-eslint-language-service' from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules: Error: Could not resolve JS module 'typescript-eslint-language-service' starting at '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules'. Looked in: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript-eslint-language-service/package.json, /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript-eslint-language-service.js, /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript-eslint-language-service.jsx, /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript-eslint-language-service/index.js, /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript-eslint-language-service/index.jsx, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/typescript-eslint-language-service/package.json, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/typescript-eslint-language-service.js, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/typescript-eslint-language-service.jsx, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/typescript-eslint-language-service/index.js, /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/typescript-eslint-language-service/index.jsx, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/typescript-eslint-language-service/package.json, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/typescript-eslint-language-service.js, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/typescript-eslint-language-service.jsx, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/typescript-eslint-language-service/index.js, /Applications/Visual Studio Code.app/Contents/Resources/node_modules/typescript-eslint-language-service/index.jsx, /Applications/Visual Studio Code.app/Contents/node_modules/typescript-eslint-language-service/package.json, /Applications/Visual Studio Code.app/Contents/node_modules/typescript-eslint-language-service.js, /Applications/Visual Studio Code.app/Contents/node_modules/typescript-eslint-language-service.jsx, /Applications/Visual Studio Code.app/Contents/node_modules/typescript-eslint-language-service/index.js, /Applications/Visual Studio Code.app/Contents/node_modules/typescript-eslint-language-service/index.jsx, /Applications/Visual Studio Code.app/node_modules/typescript-eslint-language-service/package.json, /Applications/Visual Studio Code.app/node_modules/typescript-eslint-language-service.js, /Applications/Visual Studio Code.app/node_modules/typescript-eslint-language-service.jsx, /Applications/Visual Studio Code.app/node_modules/typescript-eslint-language-service/index.js, /Applications/Visual Studio Code.app/node_modules/typescript-eslint-language-service/index.jsx, /Applications/node_modules/typescript-eslint-language-service/package.json, /Applications/node_modules/typescript-eslint-language-service.js, /Applications/node_modules/typescript-eslint-language-service.jsx, /Applications/node_modules/typescript-eslint-language-service/index.js, /Applications/node_modules/typescript-eslint-language-service/index.jsx, /node_modules/typescript-eslint-language-service/package.json, /node_modules/typescript-eslint-language-service.js, /node_modules/typescript-eslint-language-service.jsx, /node_modules/typescript-eslint-language-service/index.js, /node_modules/typescript-eslint-language-service/index.jsx
    at Object.resolveJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:44257:19)
    at sys.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:185768:49)
    at Project.resolveModule (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173477:35)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174624:36
    at Object.firstDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:221:26)
    at Project.beginEnablePluginSync (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174623:41)
    at ProjectService.requestEnablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178808:49)
    at Project.enablePlugin (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174687:37)
    at ConfiguredProject.enablePluginsWithOptions (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175358:30)
    at ProjectService.loadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177076:25)
    at ProjectService.createAndLoadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177028:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177033:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178119:44)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178459:97
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178459:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179831:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182024:96
    at Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182015:28)
    at Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182024:41)
    at Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182052:35)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:186208:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
Info 29   [16:53:28.718] Couldn't find typescript-eslint-language-service
```

Here is my `tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["dom", "es2015", "esnext.asynciterable"],
    "module": "commonjs",
    "rootDir": "./",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "types": ["node", "jest"],
    "moduleResolution": "node",
    "noEmitOnError": true,
    "sourceMap": false,
    "jsx": "react-jsx",
    "typeRoots": ["./@types", "./node_modules/@types"],
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true,
    "plugins": [
      {
        "name": "typescript-eslint-language-service"
      }
    ]
  },
  "ts-node": {
    "files": true
  },
  "files": ["./global.d.ts"],
  "include": ["**/*.ts", "**/*.tsx", "**/*.js"],
  "exclude": ["node_modules"]
}

```

Does anything need setting in the `tsconfig.json` to tell TS to look in the local `node_modules` folder?

**Comment by ebenali** [comment]
almost a year ...
